### ISSUE TITLE
Add .full-width-item utility class

### ISSUE THREAD

**Issue by cferdinandi** [mashery/blackbeard#155]
```css
/**
 * Object width
 */

.full-width {
	left: 50%;
	margin-left: -50vw;
	margin-right: -50vw;
	max-width: 100vw;
	position: relative;
	right: 50%;
	width: 100vw;
}

body {
	overflow-x: hidden;
}

#nav-primary {
	background-color: $color-white;
	border-bottom: calc-em(1px) solid $color-gray-light;
	margin-bottom: $spacing;

	.loading &,
	.page-no-heading & {
		margin-bottom: 0;
	}
}
```

```js
// Hide the title if needed
window.portalOptions.templates.page = function () {
	return	'<div class="main container container-small content" id="main">' +
				(mashery.globals.noHeading ? '' : '<h1>{{content.heading}}</h1>') +
				'{{content.main}}' +
			'</div>';
};

window.addEventListener('portalBeforeRender', function () {
	if (mashery.globals.noHeading) {
		document.documentElement.classList.add('page-no-heading');
	} else {
		document.documentElement.classList.remove('page-no-heading');
	}
}, false);
```
